from datetime import date
from decimal import Decimal

from app_users.services.demo_login_service.factories.categories import ExpenseCategoryName
from app_users.services.demo_login_service.factories.entities import DepositName, EntityName
from app_users.services.demo_login_service.factories.periods import PeriodName
from categories.models import TransferCategory
from categories.models.choices.category_type import CategoryType
from entities.models import Deposit, Entity
from periods.models import Period
from transfers.models import Expense


def create_expenses(
    daily_wallet_periods: dict[PeriodName, Period],
    long_term_wallet_periods: dict[PeriodName, Period],
    deposits: dict[DepositName, Deposit],
    entities: dict[EntityName, Entity],
    expense_categories: dict[ExpenseCategoryName, TransferCategory],
) -> None:
    """
    Service to create Expenses for demo User.
    """
    ...
    Expense.objects.bulk_create(
        [
            # DAILY Wallet PERSONAL Deposit 2026_01 Expenses
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Food",
                date=date(2026, 1, 1),
                period=daily_wallet_periods[PeriodName._2026_01],
                value=Decimal("50.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.FOOD_SELLER],
                category=expense_categories[ExpenseCategoryName.FOOD],
                description="Food",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Food",
                date=date(2026, 1, 4),
                period=daily_wallet_periods[PeriodName._2026_01],
                value=Decimal("100.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.FOOD_SELLER],
                category=expense_categories[ExpenseCategoryName.FOOD],
                description="Food",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Food",
                date=date(2026, 1, 7),
                period=daily_wallet_periods[PeriodName._2026_01],
                value=Decimal("50.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.FOOD_SELLER],
                category=expense_categories[ExpenseCategoryName.FOOD],
                description="Food",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Food",
                date=date(2026, 1, 11),
                period=daily_wallet_periods[PeriodName._2026_01],
                value=Decimal("100.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.FOOD_SELLER],
                category=expense_categories[ExpenseCategoryName.FOOD],
                description="Food",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Food",
                date=date(2026, 1, 19),
                period=daily_wallet_periods[PeriodName._2026_01],
                value=Decimal("50.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.FOOD_SELLER],
                category=expense_categories[ExpenseCategoryName.FOOD],
                description="Food",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Food",
                date=date(2026, 1, 27),
                period=daily_wallet_periods[PeriodName._2026_01],
                value=Decimal("100.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.FOOD_SELLER],
                category=expense_categories[ExpenseCategoryName.FOOD],
                description="Food",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="To common account",
                date=date(2026, 1, 1),
                period=daily_wallet_periods[PeriodName._2026_01],
                value=Decimal("5000.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=deposits[DepositName.COMMON],
                category=expense_categories[ExpenseCategoryName.TO_COMMON_ACCOUNT],
                description="Monthly transfer to common account",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Unexpected",
                date=date(2026, 1, 3),
                period=daily_wallet_periods[PeriodName._2026_01],
                value=Decimal("300.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.UNEXPECTED_ENTITY],
                category=expense_categories[ExpenseCategoryName.PERSONAL_UNEXPECTED],
                description="Unexpected",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Unexpected",
                date=date(2026, 1, 5),
                period=daily_wallet_periods[PeriodName._2026_01],
                value=Decimal("100.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.UNEXPECTED_ENTITY],
                category=expense_categories[ExpenseCategoryName.PERSONAL_UNEXPECTED],
                description="Unexpected",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Unexpected",
                date=date(2026, 1, 12),
                period=daily_wallet_periods[PeriodName._2026_01],
                value=Decimal("300.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.UNEXPECTED_ENTITY],
                category=expense_categories[ExpenseCategoryName.PERSONAL_UNEXPECTED],
                description="Unexpected",
            ),
            # DAILY Wallet PERSONAL Deposit 2026_02 Expenses
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Food",
                date=date(2026, 2, 1),
                period=daily_wallet_periods[PeriodName._2026_02],
                value=Decimal("50.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.FOOD_SELLER],
                category=expense_categories[ExpenseCategoryName.FOOD],
                description="Food",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Food",
                date=date(2026, 2, 4),
                period=daily_wallet_periods[PeriodName._2026_02],
                value=Decimal("100.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.FOOD_SELLER],
                category=expense_categories[ExpenseCategoryName.FOOD],
                description="Food",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Food",
                date=date(2026, 2, 7),
                period=daily_wallet_periods[PeriodName._2026_02],
                value=Decimal("50.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.FOOD_SELLER],
                category=expense_categories[ExpenseCategoryName.FOOD],
                description="Food",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Food",
                date=date(2026, 2, 11),
                period=daily_wallet_periods[PeriodName._2026_02],
                value=Decimal("100.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.FOOD_SELLER],
                category=expense_categories[ExpenseCategoryName.FOOD],
                description="Food",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Food",
                date=date(2026, 2, 19),
                period=daily_wallet_periods[PeriodName._2026_02],
                value=Decimal("50.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.FOOD_SELLER],
                category=expense_categories[ExpenseCategoryName.FOOD],
                description="Food",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Food",
                date=date(2026, 2, 27),
                period=daily_wallet_periods[PeriodName._2026_02],
                value=Decimal("100.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.FOOD_SELLER],
                category=expense_categories[ExpenseCategoryName.FOOD],
                description="Food",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Food",
                date=date(2026, 2, 28),
                period=daily_wallet_periods[PeriodName._2026_02],
                value=Decimal("150.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.FOOD_SELLER],
                category=expense_categories[ExpenseCategoryName.FOOD],
                description="Food",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="To common account",
                date=date(2026, 2, 1),
                period=daily_wallet_periods[PeriodName._2026_02],
                value=Decimal("5000.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=deposits[DepositName.COMMON],
                category=expense_categories[ExpenseCategoryName.TO_COMMON_ACCOUNT],
                description="Monthly transfer to common account",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Unexpected",
                date=date(2026, 2, 3),
                period=daily_wallet_periods[PeriodName._2026_02],
                value=Decimal("100.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.UNEXPECTED_ENTITY],
                category=expense_categories[ExpenseCategoryName.PERSONAL_UNEXPECTED],
                description="Unexpected",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Unexpected",
                date=date(2026, 2, 5),
                period=daily_wallet_periods[PeriodName._2026_02],
                value=Decimal("100.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.UNEXPECTED_ENTITY],
                category=expense_categories[ExpenseCategoryName.PERSONAL_UNEXPECTED],
                description="Unexpected",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Unexpected",
                date=date(2026, 2, 12),
                period=daily_wallet_periods[PeriodName._2026_02],
                value=Decimal("200.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.UNEXPECTED_ENTITY],
                category=expense_categories[ExpenseCategoryName.PERSONAL_UNEXPECTED],
                description="Unexpected",
            ),
            # DAILY Wallet PERSONAL Deposit 2026_03 Expenses
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Food",
                date=date(2026, 3, 1),
                period=daily_wallet_periods[PeriodName._2026_03],
                value=Decimal("50.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.FOOD_SELLER],
                category=expense_categories[ExpenseCategoryName.FOOD],
                description="Food",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Food",
                date=date(2026, 3, 4),
                period=daily_wallet_periods[PeriodName._2026_03],
                value=Decimal("100.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.FOOD_SELLER],
                category=expense_categories[ExpenseCategoryName.FOOD],
                description="Food",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Food",
                date=date(2026, 3, 7),
                period=daily_wallet_periods[PeriodName._2026_03],
                value=Decimal("50.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.FOOD_SELLER],
                category=expense_categories[ExpenseCategoryName.FOOD],
                description="Food",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Food",
                date=date(2026, 3, 11),
                period=daily_wallet_periods[PeriodName._2026_03],
                value=Decimal("100.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.FOOD_SELLER],
                category=expense_categories[ExpenseCategoryName.FOOD],
                description="Food",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Food",
                date=date(2026, 3, 19),
                period=daily_wallet_periods[PeriodName._2026_03],
                value=Decimal("50.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.FOOD_SELLER],
                category=expense_categories[ExpenseCategoryName.FOOD],
                description="Food",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Food",
                date=date(2026, 3, 27),
                period=daily_wallet_periods[PeriodName._2026_03],
                value=Decimal("100.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.FOOD_SELLER],
                category=expense_categories[ExpenseCategoryName.FOOD],
                description="Food",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="To common account",
                date=date(2026, 3, 1),
                period=daily_wallet_periods[PeriodName._2026_03],
                value=Decimal("5500.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=deposits[DepositName.COMMON],
                category=expense_categories[ExpenseCategoryName.TO_COMMON_ACCOUNT],
                description="Monthly transfer to common account",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Unexpected",
                date=date(2026, 3, 3),
                period=daily_wallet_periods[PeriodName._2026_03],
                value=Decimal("100.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.UNEXPECTED_ENTITY],
                category=expense_categories[ExpenseCategoryName.PERSONAL_UNEXPECTED],
                description="Unexpected",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Unexpected",
                date=date(2026, 3, 5),
                period=daily_wallet_periods[PeriodName._2026_03],
                value=Decimal("100.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.UNEXPECTED_ENTITY],
                category=expense_categories[ExpenseCategoryName.PERSONAL_UNEXPECTED],
                description="Unexpected",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Unexpected",
                date=date(2026, 3, 12),
                period=daily_wallet_periods[PeriodName._2026_03],
                value=Decimal("200.00"),
                deposit=deposits[DepositName.PERSONAL],
                entity=entities[EntityName.UNEXPECTED_ENTITY],
                category=expense_categories[ExpenseCategoryName.PERSONAL_UNEXPECTED],
                description="Unexpected",
            ),
            # DAILY Wallet COMMON Deposit 2026_01 Expenses
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Bills",
                date=date(2026, 1, 1),
                period=daily_wallet_periods[PeriodName._2026_01],
                value=Decimal("2000.00"),
                deposit=deposits[DepositName.COMMON],
                entity=entities[EntityName.BILLS_TAKER],
                category=expense_categories[ExpenseCategoryName.BILLS],
                description="Bills",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Treasury bonds",
                date=date(2026, 1, 1),
                period=daily_wallet_periods[PeriodName._2026_01],
                value=Decimal("1000.00"),
                deposit=deposits[DepositName.COMMON],
                entity=entities[EntityName.DAILY_WALLET_TREASURY_BONDS_SELLER],
                category=expense_categories[ExpenseCategoryName.TREASURY_BONDS_PURCHASE],
                description="Purchase of Treasury bonds",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="ETF",
                date=date(2026, 1, 1),
                period=daily_wallet_periods[PeriodName._2026_01],
                value=Decimal("1000.00"),
                deposit=deposits[DepositName.COMMON],
                entity=entities[EntityName.DAILY_WALLET_ETF_SELLER],
                category=expense_categories[ExpenseCategoryName.ETF_PURCHASE],
                description="Purchase of ETF",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Gold",
                date=date(2026, 1, 1),
                period=daily_wallet_periods[PeriodName._2026_01],
                value=Decimal("500.00"),
                deposit=deposits[DepositName.COMMON],
                entity=entities[EntityName.DAILY_WALLET_GOLD_SELLER],
                category=expense_categories[ExpenseCategoryName.GOLD_PURCHASE],
                description="Purchase of Gold",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Unexpected",
                date=date(2026, 1, 10),
                period=daily_wallet_periods[PeriodName._2026_01],
                value=Decimal("200.00"),
                deposit=deposits[DepositName.COMMON],
                entity=entities[EntityName.UNEXPECTED_ENTITY],
                category=expense_categories[ExpenseCategoryName.COMMON_UNEXPECTED],
                description="Unexpected",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Unexpected",
                date=date(2026, 1, 15),
                period=daily_wallet_periods[PeriodName._2026_01],
                value=Decimal("100.00"),
                deposit=deposits[DepositName.COMMON],
                entity=entities[EntityName.UNEXPECTED_ENTITY],
                category=expense_categories[ExpenseCategoryName.COMMON_UNEXPECTED],
                description="Unexpected",
            ),
            # DAILY Wallet COMMON Deposit 2026_02 Expenses
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Bills",
                date=date(2026, 2, 1),
                period=daily_wallet_periods[PeriodName._2026_02],
                value=Decimal("2000.00"),
                deposit=deposits[DepositName.COMMON],
                entity=entities[EntityName.BILLS_TAKER],
                category=expense_categories[ExpenseCategoryName.BILLS],
                description="Bills",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Treasury bonds",
                date=date(2026, 2, 1),
                period=daily_wallet_periods[PeriodName._2026_02],
                value=Decimal("1000.00"),
                deposit=deposits[DepositName.COMMON],
                entity=entities[EntityName.DAILY_WALLET_TREASURY_BONDS_SELLER],
                category=expense_categories[ExpenseCategoryName.TREASURY_BONDS_PURCHASE],
                description="Purchase of Treasury bonds",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="ETF",
                date=date(2026, 2, 1),
                period=daily_wallet_periods[PeriodName._2026_02],
                value=Decimal("1000.00"),
                deposit=deposits[DepositName.COMMON],
                entity=entities[EntityName.DAILY_WALLET_ETF_SELLER],
                category=expense_categories[ExpenseCategoryName.ETF_PURCHASE],
                description="Purchase of ETF",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Gold",
                date=date(2026, 2, 1),
                period=daily_wallet_periods[PeriodName._2026_02],
                value=Decimal("500.00"),
                deposit=deposits[DepositName.COMMON],
                entity=entities[EntityName.DAILY_WALLET_GOLD_SELLER],
                category=expense_categories[ExpenseCategoryName.GOLD_PURCHASE],
                description="Purchase of Gold",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Unexpected",
                date=date(2026, 2, 10),
                period=daily_wallet_periods[PeriodName._2026_02],
                value=Decimal("200.00"),
                deposit=deposits[DepositName.COMMON],
                entity=entities[EntityName.UNEXPECTED_ENTITY],
                category=expense_categories[ExpenseCategoryName.COMMON_UNEXPECTED],
                description="Unexpected",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Unexpected",
                date=date(2026, 2, 15),
                period=daily_wallet_periods[PeriodName._2026_02],
                value=Decimal("300.00"),
                deposit=deposits[DepositName.COMMON],
                entity=entities[EntityName.UNEXPECTED_ENTITY],
                category=expense_categories[ExpenseCategoryName.COMMON_UNEXPECTED],
                description="Unexpected",
            ),
            # DAILY Wallet COMMON Deposit 2026_03 Expenses
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Bills",
                date=date(2026, 3, 1),
                period=daily_wallet_periods[PeriodName._2026_03],
                value=Decimal("2000.00"),
                deposit=deposits[DepositName.COMMON],
                entity=entities[EntityName.BILLS_TAKER],
                category=expense_categories[ExpenseCategoryName.BILLS],
                description="Bills",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Treasury bonds",
                date=date(2026, 3, 1),
                period=daily_wallet_periods[PeriodName._2026_03],
                value=Decimal("1250.00"),
                deposit=deposits[DepositName.COMMON],
                entity=entities[EntityName.DAILY_WALLET_TREASURY_BONDS_SELLER],
                category=expense_categories[ExpenseCategoryName.TREASURY_BONDS_PURCHASE],
                description="Purchase of Treasury bonds",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="ETF",
                date=date(2026, 3, 1),
                period=daily_wallet_periods[PeriodName._2026_03],
                value=Decimal("1250.00"),
                deposit=deposits[DepositName.COMMON],
                entity=entities[EntityName.DAILY_WALLET_ETF_SELLER],
                category=expense_categories[ExpenseCategoryName.ETF_PURCHASE],
                description="Purchase of ETF",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Gold",
                date=date(2026, 3, 1),
                period=daily_wallet_periods[PeriodName._2026_03],
                value=Decimal("500.00"),
                deposit=deposits[DepositName.COMMON],
                entity=entities[EntityName.DAILY_WALLET_GOLD_SELLER],
                category=expense_categories[ExpenseCategoryName.GOLD_PURCHASE],
                description="Purchase of Gold",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Unexpected",
                date=date(2026, 3, 10),
                period=daily_wallet_periods[PeriodName._2026_03],
                value=Decimal("300.00"),
                deposit=deposits[DepositName.COMMON],
                entity=entities[EntityName.UNEXPECTED_ENTITY],
                category=expense_categories[ExpenseCategoryName.COMMON_UNEXPECTED],
                description="Unexpected",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Unexpected",
                date=date(2026, 3, 15),
                period=daily_wallet_periods[PeriodName._2026_03],
                value=Decimal("300.00"),
                deposit=deposits[DepositName.COMMON],
                entity=entities[EntityName.UNEXPECTED_ENTITY],
                category=expense_categories[ExpenseCategoryName.COMMON_UNEXPECTED],
                description="Unexpected",
            ),
            # LONG_TERM Wallet ETF Deposit 2026_01 Expenses
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="ETF value decrease",
                date=date(2026, 2, 1),
                period=long_term_wallet_periods[PeriodName._2026_02],
                value=Decimal("100.00"),
                deposit=deposits[DepositName.ETF],
                entity=entities[EntityName.ETF_VALUE_CHANGE],
                category=expense_categories[ExpenseCategoryName.ETF_VALUE_DECREASE],
                description="ETF value decrease",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="ETF value decrease",
                date=date(2026, 3, 1),
                period=long_term_wallet_periods[PeriodName._2026_03],
                value=Decimal("100.00"),
                deposit=deposits[DepositName.ETF],
                entity=entities[EntityName.ETF_VALUE_CHANGE],
                category=expense_categories[ExpenseCategoryName.ETF_VALUE_DECREASE],
                description="ETF value decrease",
            ),
            # LONG_TERM Wallet GOLD Deposit 2026_01 Expenses
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Gold value decrease",
                date=date(2026, 1, 1),
                period=long_term_wallet_periods[PeriodName._2026_01],
                value=Decimal("20.00"),
                deposit=deposits[DepositName.GOLD],
                entity=entities[EntityName.GOLD_VALUE_CHANGE],
                category=expense_categories[ExpenseCategoryName.GOLD_VALUE_DECREASE],
                description="Gold value decrease",
            ),
            Expense(
                transfer_type=CategoryType.EXPENSE,
                name="Gold value decrease",
                date=date(2026, 2, 1),
                period=long_term_wallet_periods[PeriodName._2026_02],
                value=Decimal("20.00"),
                deposit=deposits[DepositName.GOLD],
                entity=entities[EntityName.GOLD_VALUE_CHANGE],
                category=expense_categories[ExpenseCategoryName.GOLD_VALUE_DECREASE],
                description="Gold value decrease",
            ),
        ]
    )
