# Generated by Django 4.2.1 on 2023-07-06 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='import_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('headers', models.JSONField(null=True)),
                ('content', models.JSONField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
