# Generated by Django 4.2.1 on 2023-06-24 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='content',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='importfile',
            name='headers',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='file',
            field=models.FileField(upload_to='import_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
