# Generated by Django 4.2.23 on 2025-10-17 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entities", "0001_initial"),
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("category_type", models.PositiveSmallIntegerField(choices=[(1, "📈 Income"), (2, "📉 Expense")])),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "📈 01. Regular"),
                            (2, "📈 02. Irregular"),
                            (3, "📉 01. Most important"),
                            (4, "📉 02. Savings and investments"),
                            (5, "📉 03. Others"),
                        ]
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_categories",
                        to="wallets.wallet",
                    ),
                ),
                (
                    "deposit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_categories",
                        to="entities.deposit",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "transfer categories",
            },
        ),
        migrations.AddConstraint(
            model_name="transfercategory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("category_type", 1), ("priority__in", (1, 2))),
                    models.Q(("category_type", 2), ("priority__in", (3, 4, 5))),
                    _connector="OR",
                ),
                name="categories_transfercategory_correct_priority_for_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="transfercategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deposit__isnull", False)),
                fields=("wallet", "category_type", "name", "deposit"),
                name="categories_transfercategory_name_unique_for_deposit",
            ),
        ),
    ]
