# Generated by Django 4.2.23 on 2025-08-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="transfercategory",
            name="categories_transfercategory_correct_priority_for_type",
        ),
        migrations.AlterField(
            model_name="transfercategory",
            name="priority",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "📈 01. Regular"),
                    (2, "📈 02. Irregular"),
                    (3, "📉 01. Most important"),
                    (4, "📉 02. Debts"),
                    (5, "📉 03. Savings"),
                    (6, "📉 04. Others"),
                    (7, "📈 03. Deposit income"),
                    (8, "📉 05. Deposit expense"),
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="transfercategory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("category_type", 1), ("priority__in", (1, 2, 7))),
                    models.Q(("category_type", 2), ("priority__in", (3, 4, 5, 6, 8))),
                    _connector="OR",
                ),
                name="categories_transfercategory_correct_priority_for_type",
            ),
        ),
    ]
