exclude: '.git|venv|__pycache__|.pytest_cache|htmlcov|migrations|docs|docs|manage.py'
default_stages: [commit]
fail_fast: true
default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: ["--line-length", "120"]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "120"]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length", "120"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-x", "venv,test,__pycache__,.pytest_cache,htmlcov"]