# Generated by Django 4.2.3 on 2023-10-21 14:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('periods', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetingperiod',
            unique_together={('name', 'user')},
        ),
    ]
