# Generated by Django 4.2.11 on 2024-08-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_transfercategory_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transfercategory',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('budget', 'category_type', 'name', 'owner'), name='categories_transfercategory_name_unique_for_owner'),
        ),
        migrations.AddConstraint(
            model_name='transfercategory',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('budget', 'category_type', 'name'), name='categories_transfercategory_name_unique_when_no_owner'),
        ),
    ]
