# Generated by Django 4.2.10 on 2024-05-08 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0002_budgetingperiod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expense_group', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Most important'), (2, 'Debts'), (3, 'Savings'), (4, 'Others')], null=True)),
                ('income_group', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Regular'), (2, 'Irregular')], null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_categories', to='budgets.budget')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'transfer categories',
            },
        ),
    ]
