# Generated by Django 4.2.10 on 2024-04-22 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0002_budgetingperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferCategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('transfer_type', models.PositiveSmallIntegerField(choices=[(0, 'Income'), (1, 'Expense'), (2, 'Relocation')])),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_groups', to='budgets.budget')),
            ],
            options={
                'verbose_name_plural': 'transfer category groups',
                'unique_together': {('name', 'budget')},
            },
        ),
        migrations.CreateModel(
            name='TransferCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='transfers.transfercategorygroup')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'transfer categories',
            },
        ),
    ]
