# Generated by Django 4.2.10 on 2024-04-16 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budgetingperiod'),
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferCategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('transfer_type', models.PositiveSmallIntegerField(choices=[(0, 'Income'), (1, 'Expense'), (2, 'Relocation')])),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_groups', to='budgets.budget')),
            ],
            options={
                'verbose_name_plural': 'transfer category groups',
                'unique_together': {('name', 'budget')},
            },
        ),
    ]
