# Generated by Django 4.2.19 on 2025-07-27 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deposits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="entity",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_deposit", True), models.Q(("is_deposit", False), ("owner__isnull", True)), _connector="OR"
                ),
                name="entities_entity_owner_value_only_on_deposit",
            ),
        ),
    ]
