# Generated by Django 4.2.19 on 2025-07-28 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="deposit_type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "💸 For daily expenses"),
                    (2, "💰 For savings"),
                    (3, "🪙 For investments"),
                    (4, "❔ Other"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deposits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="entity",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_deposit", True), models.Q(("is_deposit", False), ("owner__isnull", True)), _connector="OR"
                ),
                name="entities_entity_owner_value_only_on_deposit",
            ),
        ),
        migrations.AddConstraint(
            model_name="entity",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("deposit_type__isnull", False), ("is_deposit", True)),
                    models.Q(("deposit_type__isnull", True), ("is_deposit", False)),
                    _connector="OR",
                ),
                name="entities_entity_deposit_type_selected_for_deposit",
            ),
        ),
    ]
