# Generated by Django 4.2.10 on 2024-04-06 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0002_budgetingperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('deposit_type', models.PositiveSmallIntegerField(choices=[(0, 'Personal'), (1, 'Common'), (2, 'Reserves'), (3, 'Investments'), (4, 'Savings')])),
                ('is_active', models.BooleanField(default=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='budgets.budget')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'budget')},
            },
        ),
    ]
