# Generated by Django 4.2.16 on 2024-10-20 07:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budgets", "0002_budgetingperiod"),
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="wallets", to="budgets.budget"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "wallets",
                "unique_together": {("name", "budget")},
            },
        ),
        migrations.CreateModel(
            name="WalletDeposit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "planned_weight",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "deposit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="wallets", to="entities.deposit"
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="deposits", to="wallets.wallet"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "wallet_deposits",
                "unique_together": {("wallet", "deposit")},
            },
        ),
    ]
