# Generated by Django 4.2.19 on 2025-03-21 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, max_length=300, null=True)),
                ("currency", models.CharField(max_length=3)),
                ("members", models.ManyToManyField(blank=True, related_name="wallets", to=settings.AUTH_USER_MODEL)),
            ],
        )
    ]
