# Generated by Django 4.2.16 on 2024-10-22 06:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entities", "0001_initial"),
        ("budgets", "0002_budgetingperiod"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="wallets", to="budgets.budget"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "wallets",
            },
        ),
        migrations.CreateModel(
            name="WalletDeposit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "planned_weight",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "deposit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="wallets", to="entities.deposit"
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="deposits", to="wallets.wallet"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "wallet_deposits",
            },
        ),
        migrations.AddConstraint(
            model_name="walletdeposit",
            constraint=models.CheckConstraint(
                check=models.Q(("planned_weight__gte", Decimal("0.00"))),
                name="wallets_walletdeposit_planned_weight_gte_0",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="walletdeposit",
            unique_together={("wallet", "deposit")},
        ),
        migrations.AlterUniqueTogether(
            name="wallet",
            unique_together={("name", "budget")},
        ),
    ]
