# Generated by Django 4.2.23 on 2025-10-31 06:13

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entities", "0001_initial"),
        ("periods", "0001_initial"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("transfer_type", models.PositiveSmallIntegerField(choices=[(1, "📈 Income"), (2, "📉 Expense")])),
                ("name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers",
                        to="categories.transfercategory",
                    ),
                ),
                (
                    "deposit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposit_transfers",
                        to="entities.deposit",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entity_transfers",
                        to="entities.entity",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="periods.budgetingperiod",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "transfers",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[],
            options={
                "verbose_name_plural": "expenses",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("transfers.transfer",),
        ),
        migrations.CreateModel(
            name="Income",
            fields=[],
            options={
                "verbose_name_plural": "incomes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("transfers.transfer",),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.CheckConstraint(
                check=models.Q(("value__gt", Decimal("0.00"))), name="transfers_transfer_value_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.CheckConstraint(
                check=models.Q(("entity", models.F("deposit")), _negated=True),
                name="transfers_transfer_deposit_and_entity_not_the_same",
            ),
        ),
    ]
