# Generated by Django 4.2.23 on 2025-08-30 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transfers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="deposit_income",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deposit_expense",
                to="transfers.transfer",
            ),
        ),
    ]
