# Generated by Django 4.2.11 on 2024-06-08 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0002_budgetingperiod'),
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='budgets.budget')),
                ('deposit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity', to='deposits.deposit')),
            ],
            options={
                'verbose_name_plural': 'entities',
                'unique_together': {('name', 'budget')},
            },
        ),
    ]
