# Generated by Django 4.2.19 on 2025-03-21 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, max_length=300, null=True)),
                ("currency", models.CharField(max_length=3)),
                ("members", models.ManyToManyField(blank=True, related_name="budgets", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="BudgetingPeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.PositiveSmallIntegerField(choices=[(1, "📝 Draft"), (2, "🟢 Active"), (3, "🔒 Closed")]),
                ),
                ("name", models.CharField(max_length=128)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="periods", to="budgets.budget"
                    ),
                ),
                ("previous_period",
                 models.ForeignKey(
                     blank=True,
                     help_text="Reference to the previous budgeting period within the same budget",
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name="next_periods",
                     to="budgets.budgetingperiod",
                 )),
            ],
            options={
                "unique_together": {("name", "budget")},
            },
        ),
    ]
