---
name: Tests

on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    env:
      SECRET_KEY: test_secret_key
      DB_USER: budget_api
      DB_PASSWORD: budget_api
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose -f docker-compose-tests.yaml run --rm backend sh -c "python manage.py wait_for_db && pytest"
      - name: Cleanup
        run: docker-compose down