---
name: Tests

on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    env:
      DEV: True
      DYNACONF_DATABASE__USER: budget_api
      DYNACONF_DATABASE__PASSWORD: budget_api
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm budget_api sh -c "pytest"
      - name: Cleanup
        run: docker-compose down